apiVersion: v1
kind: Secret
metadata:
  name: translator-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  TRANSLATOR_SESSION_SECRET: {{ .Values.secrets.sessionSecret }}
  MINIO_ROOT_USER: {{ .Values.secrets.minioRootUser }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minioRootPassword }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword }}