"""Phase 2 reset migration.

Phase 1 placeholder models have been replaced by the real ORM models in
apps/api/python/translator_api/models/. No production data exists at this
phase, so we drop the old schema and recreate from Base.metadata to keep
autogenerate honest. Future schema changes will be incremental migrations
generated by Alembic.
"""

from __future__ import annotations

from alembic import op

revision = "0002_phase2_reset"
down_revision = "0001_phase1_baseline"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("DROP SCHEMA public CASCADE")
    op.execute("CREATE SCHEMA public")
    op.execute("GRANT ALL ON SCHEMA public TO current_user")
    op.execute("GRANT ALL ON SCHEMA public TO public")


def downgrade() -> None:
    op.execute("DROP SCHEMA public CASCADE")
    op.execute("CREATE SCHEMA public")
    op.execute("GRANT ALL ON SCHEMA public TO current_user")
    op.execute("GRANT ALL ON SCHEMA public TO public")